### ISSUE TITLE
is there a way to disable jupyter service?

### ISSUE THREAD

**Issue by mr-m0nst3r** [its-a-feature/Mythic#315]
Hi there,

I'm using ubuntu 22.04 vm instance on openstack.

Build the cli is okay, but I just can't get jupyter-docker running.
It seems that the jupyter-docker can't connect to the internet, while all other dockers are working well.

So, any advice to disable jupyter, or guideline to fix this?

Appreciate.

**Comment by its-a-feature** [comment]
hm... I have seen the docker MTU being an issue before (https://mlohr.com/docker-mtu/) but it's super rare. You could try setting that to something like 1400 and giving that a try. Otherwise, you can "disable" the Jupyter service by telling Mythic that it's already running on another host. Set `JUPYTER_HOST="mythic_jupyter"` to something _other_ than `mythic_jupyter` and Mythic will think that the `mythic_jupyter` server is running on that remote host, rather than locally, so it won't try to build it.

**Comment by mr-m0nst3r** [comment]
OK, I'll try that.

I'm not quite a dev, but trying to set GOPROXY here, it seems jupyter-docker is using `ARG` from `build.env`, but for other golang dockers, it's not using the `build.env`, it'll be better if you can add it. I would like to create PRs, but not so sure the best way to do it. Just one tiny suggestion.

Will let the community know after I fixed this problem.

Thank you mate.

**Comment by mr-m0nst3r** [comment]
Hi there,

Bad news, I can't get the docker working with MTU=1450, `daemon.json` and service scripts are not working, quite strange.

Good news: the pip is installing, got the internet connections, after deleting your ip range specification on `docker-compose.yml`, the left networks config is as follows:
```
networks:
    default_network:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: mythic_if
        ipam:
            driver: default
        labels:
            - mythic_network
            - default_network
```

I think it's better to leave the user to define the desired ip range, because everybody could using different ip ranges on their LAN.

Now the golang didn't recognize build.env's GOPROXY, that's another problem, but pip is working.
Cheers.
